server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: local

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: GestorDeRestaurante

jwt:
  active: local